services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Enable persistence

  websocket-server:
    build: ./websocket-server
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=8080
    depends_on:
      - redis

  pet-dashboard:
    build: 
      context: ./pet-dashboard
      args:
        - NEXT_PUBLIC_WS_URL=${WS_URL}
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=${WS_URL}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - redis
      - websocket-server

  pet-bot:
    build: ./pet-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - redis

  # Pet behavior engine (runs autonomous updates every minute)
  pet-engine:
    build: ./pet-engine
    environment:
    - REDIS_URL=${REDIS_URL}
    - NODE_ENV=${NODE_ENV}
    depends_on:
    - redis

volumes:
  redis_data:

  