services:
  pet-dashboard:
    command: npm run dev
    volumes:
      - ./pet-dashboard:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  websocket-server:
    command: npm run dev
    volumes:
      - ./websocket-server:/app
      - /app/node_modules